# Generated by Django 3.2.13 on 2022-04-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='상품명')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('created_at', models.DateTimeField(verbose_name='작성일')),
                ('funding_amount', models.CharField(max_length=255, verbose_name='목표금액')),
                ('funding_end_date', models.CharField(max_length=255, verbose_name='펀딩 종료일')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
