# Generated by Django 3.2.13 on 2022-04-20 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_product_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AddField(
            model_name='product',
            name='users_likes',
            field=models.ManyToManyField(blank=True, related_name='product_user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
