# Generated by Django 3.2.13 on 2022-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='funding_amount',
            field=models.IntegerField(max_length=255, verbose_name='목표금액'),
        ),
    ]
