# Generated by Django 3.2.13 on 2022-04-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_product_funding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='funding_amount',
            field=models.IntegerField(blank=True, verbose_name='목표금액'),
        ),
    ]
